# Generated by Django 3.0.6 on 2020-05-24 00:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('buses', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.Buses')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.Routes')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
            },
        ),
        migrations.CreateModel(
            name='TravelClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Clients')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.Travel')),
            ],
            options={
                'verbose_name': 'Travel Client',
                'verbose_name_plural': 'Travel Clients',
            },
        ),
    ]
