# Generated by Django 3.0.6 on 2020-05-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='Arrival_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='planed_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='travel_status',
            field=models.CharField(choices=[('PLANED', 'Bus on origin station'), ('STARTED', 'Bus on origin station'), ('FINISHED', 'Travel completed')], default='PLANED', max_length=10),
        ),
    ]
