# Generated by Django 3.0.6 on 2020-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20200523_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_status',
            field=models.CharField(choices=[('PLANED', 'Travel Planed'), ('STARTED', 'Bus on origin station'), ('FINISHED', 'Travel completed')], default='PLANED', max_length=10),
        ),
    ]
