# Generated by Django 3.0.6 on 2020-05-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20200523_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='Arrival_date',
            new_name='arrival_date',
        ),
    ]
