# Generated by Django 3.0.6 on 2020-05-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20200523_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelclients',
            name='id',
        ),
        migrations.AddField(
            model_name='travel',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Travel revenue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelclients',
            name='travel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='travels.Travel'),
        ),
    ]
