# Generated by Django 3.0.6 on 2020-05-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20200523_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Travel revenue'),
        ),
    ]
