# Generated by Django 3.0.6 on 2020-05-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_auto_20200523_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclients',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelclients',
            name='travel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.Travel'),
        ),
    ]
