# Generated by Django 3.0.6 on 2020-05-24 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_auto_20200523_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclients',
            name='ticket_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Ticket Cost'),
        ),
        migrations.AlterField(
            model_name='travelclients',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='travelclients',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.Travel'),
        ),
    ]
