# Generated by Django 3.0.6 on 2020-05-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_auto_20200523_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='time_to_complete',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
