# Generated by Django 3.0.6 on 2020-05-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_travel_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='time_to_complete',
            field=models.BigIntegerField(default=0),
        ),
    ]
