# Generated by Django 3.0.6 on 2020-05-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_travel_travels_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='travels_completed',
        ),
    ]
