# Generated by Django 3.0.6 on 2020-05-24 00:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Children costs')),
                ('adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adult costs')),
                ('third_age', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Third age costs')),
                ('student', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Students costs')),
            ],
            options={
                'verbose_name': 'Cost',
                'verbose_name_plural': 'Cost',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('station_name', models.CharField(max_length=35, unique=True, verbose_name='Station name')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('travel_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Travel costs')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.Costs')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Destination_Station', to='routes.Stations')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Origin_Station', to='routes.Stations')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
