# Generated by Django 3.0.6 on 2020-05-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_remove_costs_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='people_in_station',
            field=models.BigIntegerField(default=0),
        ),
    ]
