# Generated by Django 3.0.6 on 2020-05-24 00:25

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=35, verbose_name='Name')),
                ('last_name', models.CharField(max_length=35, verbose_name='LastName')),
                ('mother_name', models.CharField(max_length=35, null=True, verbose_name='MothersName')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 5512345678. Up to 12 digits allowed.', regex='^\\d{9,12}$')])),
                ('birthday', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('disability', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
