# Generated by Django 3.0.6 on 2020-05-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=35, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='mother_name',
            field=models.CharField(max_length=35, null=True, verbose_name='Mothers Name'),
        ),
    ]
