# Generated by Django 3.0.6 on 2020-05-24 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=35, verbose_name='Brand')),
                ('model', models.CharField(max_length=35, verbose_name='Model')),
                ('car_registration', models.CharField(max_length=10, verbose_name='Car Register')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
