# Generated by Django 3.0.6 on 2020-05-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='car_registration',
            field=models.CharField(max_length=10, unique=True, verbose_name='Car Register'),
        ),
    ]
