# Generated by Django 3.0.6 on 2020-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20200523_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='clients_attended',
            field=models.BigIntegerField(default=0),
        ),
    ]
